import { EntityManager } from "typeorm";
import { Transaction } from "../../../transactions/entities/transaction.entity";
import { TransactionSplit } from "../../../transactions/entities/transaction-split.entity";
import { SplitKind } from "../../../transactions/entities/split-kind.enum";
import { roundMoney } from "../../../common/round.util";
import { MappedTransaction } from "../model/mny-import-model";
import { INSERT_CHUNK_SIZE, chunk } from "./chunk";

/**
 * Bulk writer for transactions and their splits (design ADR-9).
 *
 * Three things keep a 37,000-row file inside the time budget: ids are
 * pre-generated by the mapper, rows go in as chunked multi-row inserts rather
 * than one round trip each (which is what made PR #192's migration take hours),
 * and `linked_transaction_id` is back-patched in one `UPDATE ... FROM (VALUES)`
 * pass per chunk instead of per row.
 *
 * The back-patch exists because the column is a self-referencing foreign key:
 * inserting a transfer pair in arbitrary order would fail the constraint on
 * whichever side went first.
 */

export { INSERT_CHUNK_SIZE };

export interface WriteTransactionsInput {
  readonly transactions: readonly MappedTransaction[];
  /** Import-local account key -> Monize account id. */
  readonly accountIdByKey: ReadonlyMap<string, string>;
  /** Money `hcat` -> Monize category id, for transactions and category splits. */
  readonly categoryIdByHandle: ReadonlyMap<number, string>;
  /** Money `hpay` -> Monize payee id. */
  readonly payeeIdByHandle: ReadonlyMap<number, string>;
  /** Money `hpay` -> the payee's name, stored alongside the id. */
  readonly payeeNameByHandle: ReadonlyMap<number, string>;
  /** Called after each chunk, so the wizard's progress bar moves. */
  readonly onProgress?: (processed: number, total: number) => Promise<void>;
}

export interface WrittenTransactions {
  readonly transactionsCreated: number;
  readonly splitsCreated: number;
  readonly linksApplied: number;
  /** Account ids that received at least one row, for post-processing. */
  readonly affectedAccountIds: ReadonlySet<string>;
  /**
   * The transaction and split ids that really reached the database, so the
   * investment writer can only point `transaction_id` / `transaction_split_id`
   * at a row that exists. Both columns are foreign keys, and a violation aborts
   * the whole import rather than losing one row.
   */
  readonly writtenTransactionIds: ReadonlySet<string>;
  readonly writtenSplitIds: ReadonlySet<string>;
}

export async function writeTransactions(
  manager: EntityManager,
  userId: string,
  input: WriteTransactionsInput,
): Promise<WrittenTransactions> {
  const repo = manager.getRepository(Transaction);
  const splitRepo = manager.getRepository(TransactionSplit);
  const affectedAccountIds = new Set<string>();

  const writable = input.transactions.filter((transaction) =>
    input.accountIdByKey.has(transaction.accountKey),
  );

  let processed = 0;

  for (const batch of chunk(writable, INSERT_CHUNK_SIZE)) {
    const rows = batch.map((transaction) => {
      const accountId = input.accountIdByKey.get(
        transaction.accountKey,
      ) as string;
      affectedAccountIds.add(accountId);

      return {
        id: transaction.id,
        userId,
        accountId,
        transactionDate: transaction.transactionDate,
        amount: transaction.amount,
        currencyCode: transaction.currencyCode,
        exchangeRate: 1,
        status: transaction.status,
        payeeId:
          transaction.payeeHandle === null
            ? null
            : (input.payeeIdByHandle.get(transaction.payeeHandle) ?? null),
        payeeName:
          transaction.payeeHandle === null
            ? null
            : (input.payeeNameByHandle.get(transaction.payeeHandle) ?? null),
        categoryId:
          transaction.categoryHandle === null
            ? null
            : (input.categoryIdByHandle.get(transaction.categoryHandle) ??
              null),
        description: transaction.description,
        referenceNumber: transaction.referenceNumber,
        isSplit: transaction.splits.length > 0,
        isTransfer: transaction.isTransfer,
        // Set by the back-patch pass: the column is a self-referencing FK, so
        // the counterpart may not exist yet.
        linkedTransactionId: null,
      };
    });

    await repo.insert(rows);
    processed += rows.length;
    await input.onProgress?.(processed, writable.length);
  }

  const linksApplied = await backPatchLinks(manager, writable);
  const splits = await writeSplits(splitRepo, input, writable);

  return {
    transactionsCreated: writable.length,
    splitsCreated: splits.created,
    linksApplied,
    affectedAccountIds,
    writtenTransactionIds: new Set(
      writable.map((transaction) => transaction.id),
    ),
    writtenSplitIds: splits.ids,
  };
}

/**
 * Wires every transfer pair in one pass per chunk. Only rows whose counterpart
 * was actually inserted are patched, so a transfer whose far side sits in an
 * excluded account stays an ordinary transaction rather than pointing at nothing.
 */
async function backPatchLinks(
  manager: EntityManager,
  transactions: readonly MappedTransaction[],
): Promise<number> {
  const inserted = new Set(transactions.map((transaction) => transaction.id));
  const links = transactions
    .filter(
      (transaction) =>
        transaction.linkedTransactionId !== null &&
        inserted.has(transaction.linkedTransactionId),
    )
    .map((transaction) => [
      transaction.id,
      transaction.linkedTransactionId as string,
    ]);

  for (const batch of chunk(links, INSERT_CHUNK_SIZE)) {
    const values = batch
      .map((_, index) => `($${index * 2 + 1}::uuid, $${index * 2 + 2}::uuid)`)
      .join(", ");
    await manager.query(
      `UPDATE transactions
          SET linked_transaction_id = v.linked, is_transfer = true
         FROM (VALUES ${values}) AS v(id, linked)
        WHERE transactions.id = v.id`,
      batch.flat(),
    );
  }

  return links.length;
}

/**
 * Inserts split legs after every transaction exists, so a transfer split can
 * carry its `linked_transaction_id` straight away.
 */
async function writeSplits(
  splitRepo: ReturnType<EntityManager["getRepository"]>,
  input: WriteTransactionsInput,
  transactions: readonly MappedTransaction[],
): Promise<{ created: number; ids: ReadonlySet<string> }> {
  const inserted = new Set(transactions.map((transaction) => transaction.id));

  const rows = transactions.flatMap((transaction) =>
    transaction.splits.map((split) => ({
      // Pre-generated by the mapper, not minted here: an INVESTMENT leg's
      // embedded investment row already references this id.
      id: split.id,
      transactionId: transaction.id,
      kind: split.kind,
      categoryId:
        split.categoryHandle === null
          ? null
          : (input.categoryIdByHandle.get(split.categoryHandle) ?? null),
      transferAccountId: split.transferAccountKey
        ? (input.accountIdByKey.get(split.transferAccountKey) ?? null)
        : null,
      linkedTransactionId:
        split.linkedTransactionId !== null &&
        inserted.has(split.linkedTransactionId)
          ? split.linkedTransactionId
          : null,
      amount: roundMoney(split.amount),
      memo: split.memo,
    })),
  );

  // A transfer split with no target account would violate the table's
  // kind-exclusivity constraint; fall back to a category leg, which is what the
  // mapper already does when the far account is excluded.
  const safe = rows.map((row) =>
    row.kind === SplitKind.TRANSFER && row.transferAccountId === null
      ? { ...row, kind: SplitKind.CATEGORY }
      : row,
  );

  for (const batch of chunk(safe, INSERT_CHUNK_SIZE)) {
    await splitRepo.insert(batch);
  }

  return { created: safe.length, ids: new Set(safe.map((row) => row.id)) };
}

/**
 * Writes each account's balance once, from the file-computed totals, instead of
 * accumulating per transaction. The shared post-import processing recomputes the
 * same numbers from the rows afterwards, which is what the verification report
 * compares against.
 */
export async function writeAccountBalances(
  manager: EntityManager,
  balances: ReadonlyMap<string, number>,
): Promise<number> {
  const entries = [...balances];
  if (entries.length === 0) {
    return 0;
  }

  for (const batch of chunk(entries, INSERT_CHUNK_SIZE)) {
    const values = batch
      .map(
        (_, index) => `($${index * 2 + 1}::uuid, $${index * 2 + 2}::numeric)`,
      )
      .join(", ");
    await manager.query(
      `UPDATE accounts SET current_balance = v.balance
         FROM (VALUES ${values}) AS v(id, balance)
        WHERE accounts.id = v.id`,
      batch.flatMap(([id, balance]) => [id, roundMoney(balance)]),
    );
  }

  return entries.length;
}
