import { randomUUID } from "node:crypto";
import { EntityManager } from "typeorm";
import { Security } from "../../../securities/entities/security.entity";
import { InvestmentTransaction } from "../../../securities/entities/investment-transaction.entity";
import { Transaction } from "../../../transactions/entities/transaction.entity";
import { roundMoney } from "../../../common/round.util";
import { formatInvestmentCashPayeeName } from "../../../securities/investment-cash-payee.util";
import {
  MappedInvestmentTransaction,
  MappedSecurity,
} from "../model/mny-import-model";
import { investmentWritesOwnCashRow } from "../map/investment-cash";
import { INSERT_CHUNK_SIZE, chunk } from "./chunk";

/**
 * Bulk writers for securities, investment transactions and their cash legs.
 *
 * Same shape as the transaction writer: ids are pre-generated by the mapper,
 * rows go in as chunked multi-row inserts, and the self-referencing
 * `linked_transaction_id` (which pairs the two legs of a share transfer) is
 * back-patched in one `UPDATE ... FROM (VALUES)` pass rather than per row.
 *
 * Holdings are **not** written here. They come only from
 * `HoldingsService.rebuildAccountsFromTransactions` after these rows exist, so
 * there is one implementation of "what does this account hold" rather than an
 * importer's private second opinion -- which is how PR #192 ended up with
 * negative positions.
 */

export interface WrittenSecurities {
  /** `SEC.hsec` -> the Monize security id it landed in. */
  readonly idByHandle: ReadonlyMap<number, string>;
  readonly created: number;
  /** Securities matched to a row this user already had. */
  readonly reused: number;
}

/**
 * Creates the mapped securities, reusing any the user already has by symbol.
 *
 * Find-or-create by symbol matches how accounts, categories and payees behave,
 * so a re-import into a wiped profile is clean and a second import into a
 * populated one merges. The mapper has already made every symbol unique within
 * the import, so nothing here can collapse two securities into one.
 */
export async function writeSecurities(
  manager: EntityManager,
  userId: string,
  securities: readonly MappedSecurity[],
): Promise<WrittenSecurities> {
  const repo = manager.getRepository(Security);
  const idByHandle = new Map<number, string>();
  let created = 0;
  let reused = 0;

  if (securities.length === 0) {
    return { idByHandle, created, reused };
  }

  const existing = await repo.find({
    where: { userId },
    select: ["id", "symbol"],
  });
  const existingIdBySymbol = new Map(
    existing.map((security) => [security.symbol.toUpperCase(), security.id]),
  );

  const rows: Partial<Security>[] = [];
  for (const security of securities) {
    const already = existingIdBySymbol.get(security.symbol.toUpperCase());
    if (already) {
      idByHandle.set(security.handle, already);
      reused += 1;
      continue;
    }

    const id = randomUUID();
    idByHandle.set(security.handle, id);
    existingIdBySymbol.set(security.symbol.toUpperCase(), id);
    rows.push({
      id,
      userId,
      symbol: security.symbol,
      name: security.name,
      // Money's `sct` codes are not stable across releases, so the type is
      // left for the user rather than guessed (design 6.3).
      securityType: null,
      exchange: null,
      currencyCode: security.currencyCode,
      isActive: true,
      skipPriceUpdates: security.skipPriceUpdates,
    });
    created += 1;
  }

  for (const batch of chunk(rows, INSERT_CHUNK_SIZE)) {
    await repo.insert(batch);
  }

  return { idByHandle, created, reused };
}

/**
 * A foreign key is only worth writing when the row it names was written. The
 * sets are optional so a caller that writes investments alone (a spec, a future
 * partial re-import) keeps the mapper's ids rather than silently dropping them.
 */
function resolveReference(
  id: string | null,
  written: ReadonlySet<string> | undefined,
): string | null {
  if (id === null) {
    return null;
  }
  return written === undefined || written.has(id) ? id : null;
}

export interface WriteInvestmentsInput {
  readonly transactions: readonly MappedInvestmentTransaction[];
  /** Import-local account key -> Monize account id. */
  readonly accountIdByKey: ReadonlyMap<string, string>;
  /** `SEC.hsec` -> Monize security id. */
  readonly securityIdByHandle: ReadonlyMap<number, string>;
  readonly categoryIdByHandle: ReadonlyMap<number, string>;
  readonly payeeIdByHandle: ReadonlyMap<number, string>;
  readonly payeeNameByHandle: ReadonlyMap<number, string>;
  /** `SEC.hsec` -> symbol, for the cash leg's payee label and its
   * description of last resort. */
  readonly symbolByHandle: ReadonlyMap<number, string>;
  /**
   * Ids `writeTransactions` really inserted. A trade that adopted a banking row
   * as its cash leg, or is embedded in a split leg, points at one of these
   * through a foreign key -- so a reference to a row that was not written is
   * dropped rather than aborting the import on a constraint violation.
   */
  readonly writtenTransactionIds?: ReadonlySet<string>;
  readonly writtenSplitIds?: ReadonlySet<string>;
  readonly onProgress?: (processed: number, total: number) => Promise<void>;
}

export interface WrittenInvestments {
  readonly investmentTransactionsCreated: number;
  readonly cashTransactionsCreated: number;
  readonly linksApplied: number;
  /** Every account id that received a row, for post-processing. */
  readonly affectedAccountIds: ReadonlySet<string>;
  /** Brokerage account ids whose holdings need rebuilding. */
  readonly brokerageAccountIds: ReadonlySet<string>;
}

/**
 * Writes the investment rows and the cash movements they cause.
 *
 * A cash leg is a plain transaction in the account's cash sleeve, linked from
 * the investment row through `transaction_id`. It is not a transfer pair: the
 * brokerage side of a Monize investment pair carries no cash balance of its own,
 * so mirroring the leg there would invent a balance the Money file never had and
 * make the verification report disagree with itself.
 *
 * Not every trade needs one written. `investmentWritesOwnCashRow` is the single
 * decision: a trade Money funded from another account adopts that account's row
 * as its cash leg (issue #1212), and one embedded in a split leg has its cash
 * impact on the leg (issue #1211). Synthesizing a sleeve row for either is what
 * put a transfer in and a payment out in a register Money shows nothing in.
 *
 * The cash leg's category is Money's own, and so is its payee when the file
 * recorded one. When it did not -- which is the ordinary case for a trade --
 * the payee falls back to the activity label every other producer writes
 * (`formatInvestmentCashPayeeName`), because the alternative is the register
 * rendering a bare "-" against a row whose whole purpose is to say a trade
 * settled (issue #1204). It is the same English string a natively entered or
 * QIF-imported trade already stores, so this is consistency with the existing
 * surfaces rather than a new class of generated user data.
 */
export async function writeInvestments(
  manager: EntityManager,
  userId: string,
  input: WriteInvestmentsInput,
): Promise<WrittenInvestments> {
  // includes VOID rows: a writer, not a read -- VOID trades are imported
  // as rows so the record survives, and every effects reader excludes them.
  const investmentRepo = manager.getRepository(InvestmentTransaction);
  const transactionRepo = manager.getRepository(Transaction);
  const affectedAccountIds = new Set<string>();
  const brokerageAccountIds = new Set<string>();

  const writable = input.transactions.filter((transaction) =>
    input.accountIdByKey.has(transaction.accountKey),
  );

  let processed = 0;
  let cashTransactionsCreated = 0;

  for (const batch of chunk(writable, INSERT_CHUNK_SIZE)) {
    const cashRows: Record<string, unknown>[] = [];
    const investmentRows: Record<string, unknown>[] = [];

    for (const transaction of batch) {
      const accountId = input.accountIdByKey.get(
        transaction.accountKey,
      ) as string;
      affectedAccountIds.add(accountId);
      brokerageAccountIds.add(accountId);

      const writesOwnCashRow = investmentWritesOwnCashRow(transaction);
      const cashAccountId =
        !writesOwnCashRow || transaction.cashAccountKey === null
          ? null
          : (input.accountIdByKey.get(transaction.cashAccountKey) ?? null);
      // The sleeve row this writer is about to insert, when it is the one
      // creating the cash leg at all.
      const newCashTransactionId = cashAccountId !== null ? randomUUID() : null;
      // Otherwise the banking row Money already wrote, adopted as the cash leg.
      const adoptedCashTransactionId = resolveReference(
        transaction.cashTransactionId,
        input.writtenTransactionIds,
      );
      const transactionSplitId = resolveReference(
        transaction.transactionSplitId,
        input.writtenSplitIds,
      );
      const fundingAccountId =
        transaction.fundingAccountKey === null
          ? null
          : (input.accountIdByKey.get(transaction.fundingAccountKey) ?? null);

      const symbol =
        input.symbolByHandle.get(transaction.securityHandle) ?? null;
      const description = transaction.description ?? symbol ?? null;

      // Money's payee, id and name together -- a name with no id, or an id
      // with no name, is half a payee and the register would show whichever
      // half survived.
      const moneyPayeeId =
        transaction.payeeHandle === null
          ? null
          : (input.payeeIdByHandle.get(transaction.payeeHandle) ?? null);
      const moneyPayeeName =
        transaction.payeeHandle === null
          ? null
          : (input.payeeNameByHandle.get(transaction.payeeHandle) ?? null);
      const hasMoneyPayee = moneyPayeeId !== null && moneyPayeeName !== null;

      if (newCashTransactionId !== null) {
        affectedAccountIds.add(cashAccountId as string);
        // Rendered in the row's own currency: this writer denominates the
        // cash amount, the total and the price in `transaction.currencyCode`
        // with `exchangeRate: 1`, so quoting the label in any other currency
        // would disagree with the amount stored beside it.
        const activityPayeeName = formatInvestmentCashPayeeName({
          action: transaction.action,
          symbol,
          quantity: transaction.quantity,
          price: transaction.price,
          totalAmount: transaction.totalAmount,
          currencyCode: transaction.currencyCode,
        });
        cashRows.push({
          id: newCashTransactionId,
          userId,
          accountId: cashAccountId,
          transactionDate: transaction.transactionDate,
          amount: roundMoney(transaction.cashAmount),
          currencyCode: transaction.currencyCode,
          exchangeRate: 1,
          status: transaction.status,
          // Money's payee wins when there is one -- it is what the user
          // recorded. The synthesized label is the fallback, not an override,
          // so nothing the file carried is replaced by generated text; and it
          // is an unlinked name, exactly as the native and QIF paths write it.
          payeeId: hasMoneyPayee ? moneyPayeeId : null,
          payeeName: hasMoneyPayee ? moneyPayeeName : activityPayeeName,
          categoryId:
            transaction.categoryHandle === null
              ? null
              : (input.categoryIdByHandle.get(transaction.categoryHandle) ??
                null),
          description,
          isSplit: false,
          isTransfer: false,
          linkedTransactionId: null,
        });
      }

      investmentRows.push({
        id: transaction.id,
        userId,
        accountId,
        transactionId: newCashTransactionId ?? adoptedCashTransactionId,
        transactionSplitId,
        fundingAccountId,
        securityId:
          input.securityIdByHandle.get(transaction.securityHandle) ?? null,
        action: transaction.action,
        transactionDate: transaction.transactionDate,
        quantity: transaction.quantity,
        price: transaction.price,
        commission: transaction.commission,
        totalAmount: transaction.totalAmount,
        exchangeRate: transaction.exchangeRate,
        description,
        // Money's own cleared/void state, mapped by mapTransactionStatus. A
        // voided trade imports as a VOID row on BOTH sides -- previously only
        // the cash leg carried it, so the shares stayed counted while the cash
        // claimed not to have moved. Rows with no cash leg (splits, share
        // transfers) keep their status here too instead of dropping it.
        status: transaction.status,
        // Set by the back-patch pass: the column is a self-referencing FK, so
        // the partner leg may not exist yet.
        linkedTransactionId: null,
      });
    }

    // Cash first: the investment row's `transaction_id` references it.
    if (cashRows.length > 0) {
      await transactionRepo.insert(cashRows);
      cashTransactionsCreated += cashRows.length;
    }
    await investmentRepo.insert(investmentRows);

    processed += investmentRows.length;
    await input.onProgress?.(processed, writable.length);
  }

  const linksApplied = await backPatchInvestmentLinks(manager, writable);

  return {
    investmentTransactionsCreated: writable.length,
    cashTransactionsCreated,
    linksApplied,
    affectedAccountIds,
    brokerageAccountIds,
  };
}

/**
 * Pairs the two legs of each share transfer in one pass per chunk. Only legs
 * whose partner was actually inserted are patched, so a transfer whose far side
 * sits in an excluded account keeps its ADD/REMOVE_SHARES meaning rather than
 * pointing at nothing.
 */
async function backPatchInvestmentLinks(
  manager: EntityManager,
  transactions: readonly MappedInvestmentTransaction[],
): Promise<number> {
  const inserted = new Set(transactions.map((transaction) => transaction.id));
  const links = transactions
    .filter(
      (transaction) =>
        transaction.linkedInvestmentId !== null &&
        inserted.has(transaction.linkedInvestmentId),
    )
    .map((transaction) => [
      transaction.id,
      transaction.linkedInvestmentId as string,
    ]);

  for (const batch of chunk(links, INSERT_CHUNK_SIZE)) {
    const values = batch
      .map((_, index) => `($${index * 2 + 1}::uuid, $${index * 2 + 2}::uuid)`)
      .join(", ");
    await manager.query(
      `UPDATE investment_transactions
          SET linked_transaction_id = v.linked
         FROM (VALUES ${values}) AS v(id, linked)
        WHERE investment_transactions.id = v.id`,
      batch.flat(),
    );
  }

  return links.length;
}
