import { readFileSync } from "fs";
import { join } from "path";
import { NotFoundException } from "@nestjs/common";
import { randomUUID } from "crypto";
import { assertSafeStorageKey } from "./storage-key.util";

/**
 * `storage_key` is not always server-generated by the time a provider sees it: a
 * restore writes that column from an uploaded backup file, so whatever a crafted
 * file puts there reaches the provider verbatim.
 *
 * `LocalStorageProvider` validated it; `S3StorageProvider` did not, and put the
 * key straight into `GetObject`/`PutObject` -- addressing arbitrary objects in the
 * bucket, including outside `ATTACHMENT_S3_PREFIX`, because an S3 prefix is a
 * naming convention and not a boundary.
 */
describe("assertSafeStorageKey", () => {
  it("accepts the keys the application actually generates", () => {
    const id = randomUUID();
    expect(assertSafeStorageKey(id)).toBe(id);
    expect(assertSafeStorageKey("abc-123_XYZ")).toBe("abc-123_XYZ");
  });

  it.each([
    ["a traversal segment", "../secrets/key"],
    ["a bare parent", ".."],
    ["a single dot", "."],
    ["an absolute path", "/etc/passwd"],
    ["a separator", "other/object"],
    ["a backslash", "other\\object"],
    ["a NUL byte", "abc\u0000def"],
    ["an empty key", ""],
    ["whitespace", " "],
    ["a dotted filename", "backup.json.gz"],
    ["a wildcard", "*"],
    ["a percent escape", "%2e%2e%2fetc"],
  ])("rejects %s", (_label, key) => {
    expect(() => assertSafeStorageKey(key)).toThrow(NotFoundException);
  });

  it("rejects rather than trimming a key with a directory component", () => {
    // `basename` alone would quietly turn this into "object" and carry on, which
    // is the difference between refusing a crafted key and silently accepting a
    // different one.
    expect(() => assertSafeStorageKey("../../object")).toThrow(
      NotFoundException,
    );
  });

  it("reports a malformed key as not-found, not as a distinct error", () => {
    // A prober must not be able to tell "that key is malformed" from "that key
    // does not exist"; the second answer would confirm the first guess was
    // syntactically on target.
    try {
      assertSafeStorageKey("../x");
      throw new Error("expected a rejection");
    } catch (error) {
      expect(error).toBeInstanceOf(NotFoundException);
    }
  });

  /**
   * The asymmetry was the bug: one provider checked and the other did not. So
   * this asserts that every provider routes its key through the shared
   * validator, rather than trusting each to have remembered.
   */
  describe("every storage provider validates its key", () => {
    const providers = [
      "local-storage.provider.ts",
      "s3-storage.provider.ts",
      "database-storage.provider.ts",
    ];

    it.each(providers)("%s", (file) => {
      const source = readFileSync(join(__dirname, file), "utf-8")
        .replace(/\/\*[\s\S]*?\*\//g, "")
        .replace(/\/\/[^\n]*/g, "");

      if (file === "database-storage.provider.ts") {
        // The database provider addresses a row by primary key through a
        // parameterised query, so the key never becomes part of a path or an
        // object name and there is nothing for a separator to escape.
        expect(source).toMatch(/attachmentId/);
        return;
      }
      expect(source).toMatch(/assertSafeStorageKey/);
    });

    it("covers every provider file in this directory", () => {
      // A new provider added without a case here would leave the claim above
      // silently narrower than it reads.
      const files = readFileSync(
        join(__dirname, "..", "attachments.module.ts"),
        "utf-8",
      );
      for (const provider of [
        "LocalStorageProvider",
        "S3StorageProvider",
        "DatabaseStorageProvider",
      ]) {
        expect(files).toContain(provider);
      }
      // If the module gains a fourth provider, this count fails and the list
      // above has to grow with it.
      expect(
        (files.match(/StorageProvider,/g) ?? []).length,
      ).toBeGreaterThanOrEqual(3);
    });
  });
});
