import { NotFoundException } from "@nestjs/common";
import { basename } from "path";
import { tr } from "../../i18n/translate";

/**
 * The one validator every storage provider addresses objects through.
 *
 * Keys are server-generated UUIDs, so this never rejects a legitimate one. It
 * exists because a key is not always server-generated by the time a provider
 * sees it: `transaction_attachments.storage_key` is a column, and a **restore
 * writes that column from an uploaded backup file**. Whatever a crafted file
 * puts there reaches the provider verbatim.
 *
 * `LocalStorageProvider` had this check and `S3StorageProvider` did not, which
 * is the shape of bug the "follow the existing pattern" rule is about: the
 * S3 path took the key straight into `PutObject`/`GetObject`, so a crafted
 * `storage_key` addressed arbitrary objects in the bucket -- including outside
 * the configured `ATTACHMENT_S3_PREFIX`, since S3 keys are opaque strings and a
 * prefix is a naming convention rather than a boundary. In a bucket shared with
 * anything else, that is a read primitive: the restore copies the named object
 * to a fresh key and the user downloads it as their own attachment.
 *
 * The allowlist deliberately excludes `.` and `/`, so neither a traversal
 * segment nor a separator can be expressed at all -- which is what lets the
 * local provider derive a shard path from the key and know it stays inside its
 * base directory by construction.
 *
 * Rejections are `NotFoundException`, matching what a caller sees for a key that
 * simply is not there: a malformed key and an absent one are both "no such
 * attachment", and distinguishing them tells a prober which guess was closer.
 */

const SAFE_KEY = /^[A-Za-z0-9_-]+$/;

/** Validate `key` and return it unchanged, or throw. */
export function assertSafeStorageKey(key: string): string {
  // `basename` first: a key containing a separator must fail rather than be
  // silently trimmed to its last segment, so compare against the original.
  const candidate = basename(key ?? "");
  if (
    !candidate ||
    candidate !== key ||
    !SAFE_KEY.test(candidate) ||
    candidate.includes("\0")
  ) {
    throw new NotFoundException(
      tr("errors.attachments.notFound", "Attachment not found"),
    );
  }
  return candidate;
}
