/**
 * Display labels for the per-table counts a restore reports. Keyed by the
 * backend's `countKey` (`backend/src/backup/restore-plan.ts`); a key with no
 * label here falls back to the raw camelCase key in the dialog, which
 * `restore-labels.contract.test.ts` fails on.
 */
export const RESTORE_LABELS: Record<string, string> = {
  userPreferences: 'User Preferences',
  userCurrencyPreferences: 'Currency Preferences',
  categories: 'Categories',
  payees: 'Payees',
  payeeAliases: 'Payee Aliases',
  accounts: 'Accounts',
  tags: 'Tags',
  scheduledTransactions: 'Scheduled Transactions',
  scheduledTransactionSplits: 'Scheduled Transaction Splits',
  scheduledTransactionOverrides: 'Scheduled Transaction Overrides',
  scheduledTransactionSplitTags: 'Scheduled Transaction Split Tags',
  securities: 'Securities',
  securityPrices: 'Security Prices',
  securityTags: 'Security Tags',
  holdings: 'Holdings',
  transactions: 'Transactions',
  transactionSplits: 'Transaction Splits',
  transactionTags: 'Transaction Tags',
  transactionSplitTags: 'Transaction Split Tags',
  investmentTransactions: 'Investment Transactions',
  loanRateChanges: 'Loan Rate Changes',
  loanScenarios: 'Loan Scenarios',
  budgets: 'Budgets',
  budgetCategories: 'Budget Categories',
  budgetPeriods: 'Budget Periods',
  budgetPeriodCategories: 'Budget Period Categories',
  notificationPreferences: 'Notification Preferences',
  notificationReminders: 'Notification Reminders',
  notificationPortfolioState: 'Portfolio Movement Alerts',
  notifications: 'Notifications',
  customReports: 'Custom Reports',
  importColumnMappings: 'Import Column Mappings',
  monthlyAccountBalances: 'Monthly Account Balances',
  autoBackupSettings: 'Auto-Backup Settings',
  aiProviderConfigs: 'AI Provider Configurations',
  payeeLookupSettings: 'Payee lookup settings',
  payeeLookupUsage: 'Payee lookup usage',
  monteCarloScenarios: 'Monte Carlo Scenarios',
  monteCarloCashFlows: 'Monte Carlo Cash Flows',
  institutions: 'Institutions',
  scheduledTransactionPostings: 'Scheduled Transaction Postings',
  securityDocuments: 'Security Documents',
  transactionAttachments: 'Transaction Attachments',
  attachmentBlobs: 'Attachment Files',
  investmentReports: 'Investment Reports',
  gemStrategies: 'GEM Strategies',
  gemStrategyAccounts: 'GEM Strategy Accounts',
  gemStrategyAssets: 'GEM Strategy Assets',
  gemStrategySignals: 'GEM Strategy Signals',
};
